---
title: "Case Study 09"
author: Abby Stressinger
date: October 30, 2024
output: github_document
---
 Tracking Hurricanes!
 Analyze historical storm data from NOAA
 
```{r}
#install.packages("ggmap")
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
data(world)
data(us_states)
```

```{r}
# Download a csv from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)
```

Wrangle the data
```{r}
storms <- storm_data %>%
  mutate(Year = year(ISO_TIME)) %>%
  filter(Year >= 1950) %>% #storms from 1950-present
  mutate_if(is.numeric, function(x) .funs = ifelse(x==-999.0,NA,x)) %>% #convert -999.0 to NA
  mutate(Decade = (floor(Year / 10) * 10)) %>%
  st_as_sf(coords = c("LON","LAT"), crs = 4326)

region <- st_bbox(storms)

```

Make first plot
```{r}
ggplot(world) + 
  facet_wrap(~Decade) +
  stat_bin2d(data=storms, aes(y=st_coordinates(storms)[,2], x=st_coordinates(storms)[,1]),bins=100) +
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000)) +
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])

```

Calculate table of five states with most storms
```{r}
crs1 <- st_crs(storms)
USA <- st_transform(us_states, crs = crs1)
USA1 <- USA %>%
  select(state = NAME)

storm_states <- st_join(storms, USA1, join = st_intersects,left = F)

storm_states_2 <- storm_states %>%
  group_by(state) %>%
  summarize(storms = length(unique(NAME))) %>%
  arrange(desc(storms)) %>%
  select(state, storms) %>%
  slice(1:5)

storm_states_2
```

